Cy articles create db
ucsb-cs156-f24/team01-f24-08 pull request #43
Opened 2024-10-21 03:23 UTC by qwistaycat

Closes #38

2024-10-24 03:18 UTC, caleb-stahl reviewed
Same questions as your other PR. I think it might need to be named ARTICLES_PK but maybe double check to be sure. Other stuff looks good.

2024-10-24 03:23 UTC, obenedek20 requested changes

2024-10-24 03:23 UTC, obenedek20 commented on src/main/java/edu/ucsb/cs156/example/controllers/ArticlesController.java
> +public class ArticlesController {
ArticlesController should extend ApiController

2024-10-24 03:23 UTC, obenedek20 commented on src/main/java/edu/ucsb/cs156/example/repositories/UCSBDateRepository.java
> -   */
did you mean to remove these?

2024-10-24 03:23 UTC, obenedek20 commented on src/main/resources/db/migration/changes/Articles.json
> +                        "primaryKeyName": "CONSTRAINT_6"
I think he updated the instructions for naming Primary Keys so this should be ARTICLES_PK

2024-10-24 03:23 UTC, obenedek20 commented on src/main/resources/db/migration/changes/UCSBDates.json
> +                        "primaryKeyName": "CONSTRAINT_7"
Might need to pull from main, this is a fix they implemented a few days ago so shouldn't change it

Could also just unstage it

2024-10-25 18:00 UTC, obenedek20 approved these changes

2024-10-25 18:00 UTC, merged